/*
Opendata YTJ-Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ytjclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostOffice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostOffice{}

// PostOffice Postiosoitteet
type PostOffice struct {
	// Postitoimipaikka
	City string `json:"city"`
	// [Kielikoodi](/opendata-ytj-api/v3/description?code=KIELI&lang=fi) 
	LanguageCode string `json:"languageCode"`
	// Kuntakoodi
	MunicipalityCode NullableString `json:"municipalityCode,omitempty"`
}

type _PostOffice PostOffice

// NewPostOffice instantiates a new PostOffice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostOffice(city string, languageCode string) *PostOffice {
	this := PostOffice{}
	this.City = city
	this.LanguageCode = languageCode
	return &this
}

// NewPostOfficeWithDefaults instantiates a new PostOffice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostOfficeWithDefaults() *PostOffice {
	this := PostOffice{}
	return &this
}

// GetCity returns the City field value
func (o *PostOffice) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *PostOffice) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *PostOffice) SetCity(v string) {
	o.City = v
}

// GetLanguageCode returns the LanguageCode field value
func (o *PostOffice) GetLanguageCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LanguageCode
}

// GetLanguageCodeOk returns a tuple with the LanguageCode field value
// and a boolean to check if the value has been set.
func (o *PostOffice) GetLanguageCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LanguageCode, true
}

// SetLanguageCode sets field value
func (o *PostOffice) SetLanguageCode(v string) {
	o.LanguageCode = v
}

// GetMunicipalityCode returns the MunicipalityCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostOffice) GetMunicipalityCode() string {
	if o == nil || IsNil(o.MunicipalityCode.Get()) {
		var ret string
		return ret
	}
	return *o.MunicipalityCode.Get()
}

// GetMunicipalityCodeOk returns a tuple with the MunicipalityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostOffice) GetMunicipalityCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MunicipalityCode.Get(), o.MunicipalityCode.IsSet()
}

// HasMunicipalityCode returns a boolean if a field has been set.
func (o *PostOffice) HasMunicipalityCode() bool {
	if o != nil && o.MunicipalityCode.IsSet() {
		return true
	}

	return false
}

// SetMunicipalityCode gets a reference to the given NullableString and assigns it to the MunicipalityCode field.
func (o *PostOffice) SetMunicipalityCode(v string) {
	o.MunicipalityCode.Set(&v)
}
// SetMunicipalityCodeNil sets the value for MunicipalityCode to be an explicit nil
func (o *PostOffice) SetMunicipalityCodeNil() {
	o.MunicipalityCode.Set(nil)
}

// UnsetMunicipalityCode ensures that no value is present for MunicipalityCode, not even an explicit nil
func (o *PostOffice) UnsetMunicipalityCode() {
	o.MunicipalityCode.Unset()
}

func (o PostOffice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostOffice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["city"] = o.City
	toSerialize["languageCode"] = o.LanguageCode
	if o.MunicipalityCode.IsSet() {
		toSerialize["municipalityCode"] = o.MunicipalityCode.Get()
	}
	return toSerialize, nil
}

func (o *PostOffice) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"city",
		"languageCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostOffice := _PostOffice{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostOffice)

	if err != nil {
		return err
	}

	*o = PostOffice(varPostOffice)

	return err
}

type NullablePostOffice struct {
	value *PostOffice
	isSet bool
}

func (v NullablePostOffice) Get() *PostOffice {
	return v.value
}

func (v *NullablePostOffice) Set(val *PostOffice) {
	v.value = val
	v.isSet = true
}

func (v NullablePostOffice) IsSet() bool {
	return v.isSet
}

func (v *NullablePostOffice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostOffice(val *PostOffice) *NullablePostOffice {
	return &NullablePostOffice{value: val, isSet: true}
}

func (v NullablePostOffice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostOffice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


