/*
Opendata YTJ-Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ytjclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompanyWebsite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyWebsite{}

// CompanyWebsite Yrityksen verkkosivut
type CompanyWebsite struct {
	// Verkkosivut
	Url string `json:"url"`
	RegistrationDate NullableString `json:"registrationDate,omitempty"`
	// <a aria-label=\"Tietolähde, avautuu uudessa ikkunassa\" rel=\"noopener\" href=\"/opendata-ytj-api/v3/description?code=TLAHDE&lang=fi\">Tietolähde <svg width=\"15\" height=\"14\" viewBox=\"0 -9 24 24\"> <path margin=\"0\" fill=\"#035ca7\" d=\"M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708\"></path></svg></a> 
	Source string `json:"source"`
}

type _CompanyWebsite CompanyWebsite

// NewCompanyWebsite instantiates a new CompanyWebsite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyWebsite(url string, source string) *CompanyWebsite {
	this := CompanyWebsite{}
	this.Url = url
	this.Source = source
	return &this
}

// NewCompanyWebsiteWithDefaults instantiates a new CompanyWebsite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyWebsiteWithDefaults() *CompanyWebsite {
	this := CompanyWebsite{}
	return &this
}

// GetUrl returns the Url field value
func (o *CompanyWebsite) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CompanyWebsite) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CompanyWebsite) SetUrl(v string) {
	o.Url = v
}

// GetRegistrationDate returns the RegistrationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyWebsite) GetRegistrationDate() string {
	if o == nil || IsNil(o.RegistrationDate.Get()) {
		var ret string
		return ret
	}
	return *o.RegistrationDate.Get()
}

// GetRegistrationDateOk returns a tuple with the RegistrationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyWebsite) GetRegistrationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RegistrationDate.Get(), o.RegistrationDate.IsSet()
}

// HasRegistrationDate returns a boolean if a field has been set.
func (o *CompanyWebsite) HasRegistrationDate() bool {
	if o != nil && o.RegistrationDate.IsSet() {
		return true
	}

	return false
}

// SetRegistrationDate gets a reference to the given NullableString and assigns it to the RegistrationDate field.
func (o *CompanyWebsite) SetRegistrationDate(v string) {
	o.RegistrationDate.Set(&v)
}
// SetRegistrationDateNil sets the value for RegistrationDate to be an explicit nil
func (o *CompanyWebsite) SetRegistrationDateNil() {
	o.RegistrationDate.Set(nil)
}

// UnsetRegistrationDate ensures that no value is present for RegistrationDate, not even an explicit nil
func (o *CompanyWebsite) UnsetRegistrationDate() {
	o.RegistrationDate.Unset()
}

// GetSource returns the Source field value
func (o *CompanyWebsite) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CompanyWebsite) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CompanyWebsite) SetSource(v string) {
	o.Source = v
}

func (o CompanyWebsite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyWebsite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if o.RegistrationDate.IsSet() {
		toSerialize["registrationDate"] = o.RegistrationDate.Get()
	}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *CompanyWebsite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyWebsite := _CompanyWebsite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyWebsite)

	if err != nil {
		return err
	}

	*o = CompanyWebsite(varCompanyWebsite)

	return err
}

type NullableCompanyWebsite struct {
	value *CompanyWebsite
	isSet bool
}

func (v NullableCompanyWebsite) Get() *CompanyWebsite {
	return v.value
}

func (v *NullableCompanyWebsite) Set(val *CompanyWebsite) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyWebsite) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyWebsite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyWebsite(val *CompanyWebsite) *NullableCompanyWebsite {
	return &NullableCompanyWebsite{value: val, isSet: true}
}

func (v NullableCompanyWebsite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyWebsite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


